name: zaucy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_slidable: ^4.0.0
  lottie: ^3.3.1
  audioplayers: ^6.1.1 
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  pinput: ^5.0.1
  carousel_slider_x: ^6.0.7
  font_awesome_metadata: ^1.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/Just eat courier order offer sound effect.mp3
  - assets/Coupon Posters/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/LobsterTwo-BoldItalic.ttf
          weight: 700